package school;


import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.BorderFactory;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.border.Border;


public class LoginForm extends javax.swing.JFrame {
 Connection con=null;
    PreparedStatement ps=null;
    ResultSet rs=null;
    /**
     * Creates new form LoginForm
     */
    public LoginForm() {
        initComponents();
        this.setLocationRelativeTo(null);// center form in the screen
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        usertext = new javax.swing.JTextField();
        passtext = new javax.swing.JPasswordField();
        login = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        s_register = new javax.swing.JLabel();
        t_register = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("login form");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(236, 239, 243), new java.awt.Color(236, 239, 243), new java.awt.Color(236, 239, 243), new java.awt.Color(236, 239, 243)));

        usertext.setBackground(new java.awt.Color(236, 239, 243));
        usertext.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        usertext.setForeground(new java.awt.Color(153, 153, 153));
        usertext.setText("username");
        usertext.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                usertextFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                usertextFocusLost(evt);
            }
        });

        passtext.setBackground(new java.awt.Color(236, 239, 243));
        passtext.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        passtext.setForeground(new java.awt.Color(153, 153, 153));
        passtext.setText("password");
        passtext.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passtextFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                passtextFocusLost(evt);
            }
        });

        login.setBackground(new java.awt.Color(0, 102, 102));
        login.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        login.setForeground(new java.awt.Color(255, 255, 255));
        login.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/login.png"))); // NOI18N
        login.setText("Login");
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/school.jpg"))); // NOI18N
        jPanel3.add(jLabel2);
        jLabel2.setBounds(40, 50, 260, 210);

        s_register.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        s_register.setForeground(new java.awt.Color(51, 51, 51));
        s_register.setText(" register as a student");
        s_register.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        s_register.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                s_registerMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                s_registerMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                s_registerMouseExited(evt);
            }
        });
        jPanel3.add(s_register);
        s_register.setBounds(100, 270, 140, 30);

        t_register.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        t_register.setText(" register as a teacher");
        t_register.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        t_register.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                t_registerMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                t_registerMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                t_registerMouseExited(evt);
            }
        });
        jPanel3.add(t_register);
        t_register.setBounds(100, 310, 127, 17);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Login ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 125, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(passtext, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(usertext, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(93, 93, 93))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(login, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                        .addGap(36, 36, 36)
                        .addComponent(usertext, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(passtext, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(login, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(208, 208, 208)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(209, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void s_registerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_s_registerMouseClicked
        StudentRegisterForm rgf = new StudentRegisterForm ();
        rgf.setVisible(true);
        rgf.pack();
        rgf.setLocationRelativeTo(null);
        rgf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
       this.dispose();
    }//GEN-LAST:event_s_registerMouseClicked

    private void t_registerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t_registerMouseClicked
        // TODO add your handling code here:
                TeacherRegisterForm rgf = new TeacherRegisterForm();
        rgf.setVisible(true);
        rgf.pack();
        rgf.setLocationRelativeTo(null);
        rgf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
       this.dispose();

    }//GEN-LAST:event_t_registerMouseClicked

    private boolean verify(String u, String p){
        
      if(u.equals("username") ||u.equals("")){ JOptionPane.showMessageDialog(null,"username is missing "); return false;
}
      if(p.equals("password")||p.equals("")){  JOptionPane.showMessageDialog(null,"password is missing ");return false;
}
return true;
    }
    private void s_registerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_s_registerMouseEntered
        Border label_border=BorderFactory.createMatteBorder(0,0,1,0,Color.white);
        s_register.setBorder(label_border);
    }//GEN-LAST:event_s_registerMouseEntered

    private void s_registerMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_s_registerMouseExited
        // TODO add your handling code here:
        s_register.setBorder(null);
    }//GEN-LAST:event_s_registerMouseExited

    private void t_registerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t_registerMouseEntered
Border label_border=BorderFactory.createMatteBorder(0,0,1,0,Color.white);
        t_register.setBorder(label_border);    }//GEN-LAST:event_t_registerMouseEntered

    private void t_registerMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t_registerMouseExited
        // TODO add your handling code here:
         t_register.setBorder(null); 
    }//GEN-LAST:event_t_registerMouseExited

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
        // TODO add your handling code here:
        String username=usertext.getText();
        String password=passtext.getText();
        if(verify(username,password)){
            String sql= "SELECT * FROM `users` WHERE `username`='"+username+"' AND `password`='"+password+"'";
            con=Connect.ConnectDB();

            try {
                ps=con.prepareStatement(sql);
                rs=ps.executeQuery();
                if (rs.next()){
                    if(rs.getString("user_type").equals("admin")){
                        new admin_dashboard().setVisible(true);}
                    else if(rs.getString("user_type").equals("student")){
                        new student_dashboard(rs.getString("userID")).setVisible(true);

                    }
                    else if(rs.getString("user_type").equals("teacher")){
                        new teacher_dashboard(rs.getString("userID")).setVisible(true);
                    }

                    this.setVisible(false);

                }
                else{
                    JOptionPane.showMessageDialog(null,"acces denied ");
                }

            }  catch (SQLException ex) {
                java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }
        }

    }//GEN-LAST:event_loginActionPerformed

    private void passtextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passtextFocusLost
        // TODO add your handling code here:
        String pass=String.valueOf(passtext.getPassword());
        if (pass.trim().equals("")
            || pass.trim().toLowerCase().equals("password"))
        {
            passtext.setText("password");
            passtext.setForeground(new Color(153,153,153));
        }

    }//GEN-LAST:event_passtextFocusLost

    private void passtextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passtextFocusGained
        // TODO add your handling code here:
        //clear the password on focus if the text is "password"
        //get the pass text
        String pass=String.valueOf(passtext.getPassword());
        if(pass.trim().toLowerCase().equals("password"))
        {
            passtext.setText("");
            passtext.setForeground(Color.black);

        }

    }//GEN-LAST:event_passtextFocusGained

    private void usertextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usertextFocusLost
        // TODO add your handling code here:
        //if the text is equal to username or empty
        //we will set the "username" test in the field
        //on focus lost event
        if (usertext.getText().trim().equals("")
            || usertext.getText().trim().toLowerCase().equals("username"))
        {
            usertext.setText("username");
            usertext.setForeground(new Color(153,153,153));}
    }//GEN-LAST:event_usertextFocusLost

    private void usertextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usertextFocusGained
        // TODO add your handling code here:
        //clear the textfield on focus if the text is "username"
        if(usertext.getText().trim().toLowerCase().equals("username"))
        {
            usertext.setText("");
            usertext.setForeground(Color.black);

        }
    }//GEN-LAST:event_usertextFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton login;
    private javax.swing.JPasswordField passtext;
    private javax.swing.JLabel s_register;
    private javax.swing.JLabel t_register;
    private javax.swing.JTextField usertext;
    // End of variables declaration//GEN-END:variables
}
